### ISSUE TITLE
Fail to get devices from Mainland of China

### ISSUE THREAD

**Issue by xmasrain** [shenxn/libdyson#20]
![image](https://user-images.githubusercontent.com/58833842/146666552-08f7b983-ae53-4e57-bcc6-241ad51f0a36.png)

**Comment by Kakise** [comment]
Hello, sometimes you need to disconnect and reconnect from the Dyson Link app for it to work, could you try that and tell me if it works please ?

**Comment by xmasrain** [comment]
![image](https://user-images.githubusercontent.com/58833842/146671605-65aa2596-bdc1-40f5-9e70-097ad8860ef4.png)
I have tried 3 methods :1st directly log in with the get_devices.py, failed ; 2nd log out from my Dyson link then log in with the get_devices.py, failed; 3rd log out from my Dyson link and log in Dyson link again, then log in with the get_devices.py, failed.

**Comment by Kakise** [comment]
I bumped libdyson to v0.8.11, it should fix the issue with CN region. Please try again, don't forget to logout of the app (don't uninstall it without logging out first)
